apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: external-dns-monitoring-rules
  namespace: monitoring
spec:
  groups:
  - name: external-dns.rules
    rules:
    - alert: ExternalDNSLastSyncWarning
      expr: (time() - external_dns_controller_last_sync_timestamp_seconds{pod=~".*external-dns.*",pod=~"$pod"}) > 600
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "ExternalDNS last sync warning"
        description: "The last sync timestamp of ExternalDNS pod {{ $labels.pod }} is more than 10 minutes old."
    - alert: ExternalDNSLastSyncCritical
      expr: (time() - external_dns_controller_last_sync_timestamp_seconds{pod=~".*external-dns.*",pod=~"$pod"}) > 1800
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "ExternalDNS last sync critical"
        description: "The last sync timestamp of ExternalDNS pod {{ $labels.pod }} is more than 30 minutes old."
    - alert: ExternalDNSRegistryErrorsWarning
      expr: increase(external_dns_registry_errors_total{pod=~".*external-dns.*",pod=~"$pod"}[5m]) >= 1
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "ExternalDNS registry errors warning"
        description: "The count of registry errors in ExternalDNS pod {{ $labels.pod }} has increased by 1 or more in the last 5 minutes."
    - alert: ExternalDNSRegistryErrorsCritical
      expr: increase(external_dns_registry_errors_total{pod=~".*external-dns.*",pod=~"$pod"}[5m]) >= 3
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "ExternalDNS registry errors critical"
        description: "The count of registry errors in ExternalDNS pod {{ $labels.pod }} has increased by 3 or more in the last 5 minutes."
    - alert: ExternalDNSSourceErrorsWarning
      expr: increase(external_dns_source_errors_total{pod=~".*external-dns.*",pod=~"$pod"}[5m]) >= 1
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "ExternalDNS source errors warning"
        description: "The count of source errors in ExternalDNS pod {{ $labels.pod }} has increased by 1 or more in the last 5 minutes."
    - alert: ExternalDNSSourceErrorsCritical
      expr: increase(external_dns_source_errors_total{pod=~".*external-dns.*",pod=~"$pod"}[5m]) >= 3
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "ExternalDNS source errors critical"
        description: "The count of source errors in ExternalDNS pod {{ $labels.pod }} has increased by 3 or more in the last 5 minutes."
    - alert: ExternalDNSMemoryUtilizationHigh
      expr: container_memory_usage_bytes{pod=~".*external-dns.*"} / container_spec_memory_limit_bytes{pod=~".*external-dns.*"} * 100 > 70
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "ExternalDNS memory utilization high"
        description: "Memory utilization of ExternalDNS pod {{ $labels.pod }} is above 70%."
    - alert: ExternalDNSCPUUtilizationHigh
      expr: rate(container_cpu_usage_seconds_total{pod=~".*external-dns.*"}[5m]) / container_spec_cpu_quota{pod=~".*external-dns.*"} * 100 > 70
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "ExternalDNS CPU utilization high"
        description: "CPU utilization of ExternalDNS pod {{ $labels.pod }} is above 70%."